services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=dckx3i=4u0gVMh3yz1js
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  #    networks:
  #      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    #      - ELASTICSEARCH_USERNAME=kibana_system
    #     - ELASTICSEARCH_PASSWORD=
    #      - ELASTICSEARCH_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjptS3Q2X3hjdlQySzJjRWJieVNPbkFR
    ports:
      - "5601:5601"
  #    networks:
  #      - elk

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.17.4
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    environment:
      - strict.perms=false
    #    networks:
    #      - elk
    depends_on:
      - elasticsearch

volumes:
  es_data:

networks:
  elk:
    driver: bridge
